# Generated by Django 4.0.4 on 2022-05-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
