# Generated by Django 4.0.4 on 2022-05-02 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0002_alter_comments_pub_date_alter_posts_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('comment_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 5, 2, 14, 59, 16, 159454, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('post_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 5, 2, 14, 59, 16, 133368, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opinions.post'),
        ),
    ]
